### ISSUE TITLE
Deberían declararse constantes para los márgenes

### ISSUE THREAD

**Issue by didierrenardub** [TomasDamonte/Universys_MobileTeam#10]
https://github.com/TomasDamonte/Universys_MobileTeam/blob/10d0eab4165191aea71954484d797005e756bcf4/app/src/main/java/universis/universys/AlumnoMain.java#L369-L370

Si después se quiere cambiar el margen, debe modificarse en al menos 8 lugares. Si, en su lugar, se define una constante, sólo se modificaría en uno.

**Comment by TomasDamonte** [comment]
Resuelto.
