### ISSUE TITLE
Se usa esta clase?

### ISSUE THREAD

**Issue by didierrenardub** [TomasDamonte/Universys_MobileTeam#2]
https://github.com/TomasDamonte/Universys_MobileTeam/blob/10d0eab4165191aea71954484d797005e756bcf4/app/src/androidTest/java/universis/universys/ExampleInstrumentedTest.java#L1

No debería haber clases inservibles en ningún caso, y aumenta la gravedad al estar en un branch de integración y no personal o de feature.

**Comment by TomasDamonte** [comment]
Clase generada de forma automatica por gradle.

**Comment by TomasDamonte** [comment]
Clase eliminada.
