### ISSUE TITLE
Se usa esta clase?

### ISSUE THREAD

**Issue by didierrenardub** [TomasDamonte/Universys_MobileTeam#3]
https://github.com/TomasDamonte/Universys_MobileTeam/blob/10d0eab4165191aea71954484d797005e756bcf4/app/src/test/java/universis/universys/ExampleUnitTest.java#L1

Idem issue anterior.

**Comment by TomasDamonte** [comment]
Clase generada automaticamente por gradle.

**Comment by TomasDamonte** [comment]
Clase eliminada.
