### ISSUE TITLE
Debería hacerse una función

### ISSUE THREAD

**Issue by didierrenardub** [TomasDamonte/Universys_MobileTeam#6]
https://github.com/TomasDamonte/Universys_MobileTeam/blob/10d0eab4165191aea71954484d797005e756bcf4/app/src/main/java/universis/universys/AlumnoMain.java#L214-L215

Este es código potencialmente reusable en otras funciones, por lo que no estaría mal hacer una función "closeDrawer()" que contenga esto. Le dará más claridad.

**Comment by TomasDamonte** [comment]
Resuelto.
