### ISSUE TITLE
Try-catch poco eficiente

### ISSUE THREAD

**Issue by didierrenardub** [TomasDamonte/Universys_MobileTeam#8]
https://github.com/TomasDamonte/Universys_MobileTeam/blob/10d0eab4165191aea71954484d797005e756bcf4/app/src/main/java/universis/universys/AlumnoMain.java#L238-L248

Try-catch es una operación costosa, y se gasta proceso al ingresar dentro de un bloque de esa índole. En consecuencia, es más efectivo try-catchear todo el for en lugar de su contenido.

**Comment by federicoferreiro** [comment]
Solucionado.

Se debio poner el TRY por encima del FOR y el CATCH bajarse dos { para que quede el FOR por dentro

En la actualizacion de la fecha de hoy se subira el cambio
