### ISSUE TITLE
Creación de funciones para mejorar legibilidad

### ISSUE THREAD

**Issue by didierrenardub** [TomasDamonte/Universys_MobileTeam#9]
https://github.com/TomasDamonte/Universys_MobileTeam/blob/10d0eab4165191aea71954484d797005e756bcf4/app/src/main/java/universis/universys/AlumnoMain.java#L253-L266

Poner cada uno de estos bloques en una función (por ejemplo en este caso "taskDatosPersonales()" o lo que corresponda), de esa manera este método queda más legible y por ende de mejor calidad.

**Comment by TomasDamonte** [comment]
Resuelto.
